policies:
  network_segmentation:
    enabled: true
    rules:
      - name: "swift-network-isolation"
        priority: 100
        description: "Enforce SWIFT network isolation"
        conditions:
          - type: "NetworkAccess"
            source: "External"
            destination: "SWIFT-Network"
            action: "Deny"
            exceptions:
              - source_ip: "authorized-payment-gateway"
                ports: [443]
                protocols: ["HTTPS"]

      - name: "pci-network-isolation"
        priority: 200
        description: "Enforce PCI-DSS network isolation"
        conditions:
          - type: "NetworkAccess"
            source: "*"
            destination: "PCI-Network"
            action: "Deny"
            exceptions:
              - source_ip: "payment-processor"
                ports: [443, 8443]
                protocols: ["HTTPS"]

  encryption:
    enabled: true
    requirements:
      key_vault:
        sku: "Premium"
        soft_delete: true
        purge_protection: true
      keys:
        type: "RSA-HSM"
        key_size: 4096
        rotation_policy:
          days: 90
          auto_rotate: true

  compliance:
    frameworks:
      - name: "PCI-DSS"
        version: "3.2.1"
        controls:
          - id: "1.1"
            enabled: true
            validation_frequency: "PT5M"
          - id: "3.4"
            enabled: true
            validation_frequency: "PT1M"
      
      - name: "SWIFT-SCR"
        version: "2023"
        controls:
          - id: "2.1"
            enabled: true
            validation_frequency: "PT1M"